# Generated by Django 4.1 on 2022-10-28 02:19

from django.db import migrations, models
import uhealths.models


class Migration(migrations.Migration):

    dependencies = [
        ('uhealths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', uhealths.models.UserProfileManger()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bmi',
            field=models.IntegerField(default=0, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bmr',
            field=models.IntegerField(default=0, verbose_name='BMR'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=0, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Weight'),
        ),
    ]
